SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
/****** Object:  View dbo.ACCOUNT_CHAR_VIEW    Script Date: 6/6/2006 6:03:32 PM ******/
CREATE VIEW [dbo].[ACCOUNT_CHAR_VIEW]
AS SELECT [dbo].[ACCOUNT_CHAR].[strAccountID]
FROM [dbo].[ACCOUNT_CHAR]

GO
