SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[CLEAR_REMAIN_USERS]
@AccountID	varchar(50)
AS
BEGIN TRAN
	DELETE FROM CURRENTUSER WHERE strAccountID = @AccountID
	TRUNCATE TABLE CURRENTUSER
COMMIT TRAN
GO
