CREATE TABLE [dbo].[ITEMUP_PROBABILITY]
(
[bType] [tinyint] NOT NULL,
[nMaxSuccess] [smallint] NOT NULL CONSTRAINT [DF_ITEMUP_PROBABILITY_nProbability] DEFAULT (0),
[nMaxFail] [smallint] NOT NULL CONSTRAINT [DF_ITEMUP_PROBABILITY_nMaxFail] DEFAULT (0),
[nCurSuccess] [smallint] NOT NULL CONSTRAINT [DF_ITEMUP_PROBABILITY_nCurSuccess] DEFAULT (0),
[nCurFail] [smallint] NOT NULL CONSTRAINT [DF_ITEMUP_PROBABILITY_nCurFail] DEFAULT (0)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ITEMUP_PROBABILITY] ADD CONSTRAINT [PK_ITEMUP_PROBABILITY] PRIMARY KEY CLUSTERED  ([bType]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
