CREATE TABLE [dbo].[SKILL]
(
[Lv] [text] COLLATE Latin1_General_CI_AI NULL,
[Pic] [text] COLLATE Latin1_General_CI_AI NULL,
[HpMax] [text] COLLATE Latin1_General_CI_AI NULL,
[MpMax] [text] COLLATE Latin1_General_CI_AI NULL,
[ResHp] [text] COLLATE Latin1_General_CI_AI NULL,
[Soul] [text] COLLATE Latin1_General_CI_AI NULL,
[totAddMin] [text] COLLATE Latin1_General_CI_AI NULL,
[totAddMax] [text] COLLATE Latin1_General_CI_AI NULL,
[totSubAddMin] [text] COLLATE Latin1_General_CI_AI NULL,
[totSubAddMax] [text] COLLATE Latin1_General_CI_AI NULL,
[curMaxPoint] [text] COLLATE Latin1_General_CI_AI NULL,
[ReqLv] [text] COLLATE Latin1_General_CI_AI NULL,
[curAddMin] [text] COLLATE Latin1_General_CI_AI NULL,
[curAddMax] [text] COLLATE Latin1_General_CI_AI NULL,
[curSubMaxPoint] [text] COLLATE Latin1_General_CI_AI NULL,
[curSubAddMin] [text] COLLATE Latin1_General_CI_AI NULL,
[curSubAddMax] [text] COLLATE Latin1_General_CI_AI NULL,
[Success] [text] COLLATE Latin1_General_CI_AI NULL,
[Type3] [text] COLLATE Latin1_General_CI_AI NULL,
[Type4] [text] COLLATE Latin1_General_CI_AI NULL,
[Type5] [text] COLLATE Latin1_General_CI_AI NULL,
[Dist] [text] COLLATE Latin1_General_CI_AI NULL,
[DmgMin1] [text] COLLATE Latin1_General_CI_AI NULL,
[DmgMax1] [text] COLLATE Latin1_General_CI_AI NULL,
[DmgMin2] [text] COLLATE Latin1_General_CI_AI NULL,
[DmgMax2] [text] COLLATE Latin1_General_CI_AI NULL,
[Interval] [text] COLLATE Latin1_General_CI_AI NULL,
[NeedStuff1] [text] COLLATE Latin1_General_CI_AI NULL,
[Count1] [text] COLLATE Latin1_General_CI_AI NULL,
[NeedStuff2] [text] COLLATE Latin1_General_CI_AI NULL,
[Count2] [text] COLLATE Latin1_General_CI_AI NULL,
[NeedStuff3] [text] COLLATE Latin1_General_CI_AI NULL,
[Count3] [text] COLLATE Latin1_General_CI_AI NULL,
[NeedStuff4] [text] COLLATE Latin1_General_CI_AI NULL,
[Count4] [text] COLLATE Latin1_General_CI_AI NULL,
[NickName] [text] COLLATE Latin1_General_CI_AI NULL,
[Explain] [text] COLLATE Latin1_General_CI_AI NULL
) ON [PRIMARY]
GO
