CREATE TABLE [dbo].[USERDATA_SKILLSHORTCUT]
(
[strCharID] [char] (21) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_USERDATA_SKILLSHORTCUT_strCharID] DEFAULT (''),
[nCount] [smallint] NOT NULL CONSTRAINT [DF_USERDATA_SKILLSHORTCUT_nCount] DEFAULT (0),
[strSkillData] [varchar] (260) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_USERDATA_SKILLSHORTCUT_strSkillData] DEFAULT (0x00)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[USERDATA_SKILLSHORTCUT] ADD CONSTRAINT [PK_USERDATA_SKILLSHORTCUT] PRIMARY KEY CLUSTERED  ([strCharID]) ON [PRIMARY]
GO
