CREATE TABLE [dbo].[CHAR_BASE_ABILITY]
(
[Tribe] [text] COLLATE Latin1_General_CI_AI NULL,
[Str] [text] COLLATE Latin1_General_CI_AI NULL,
[Dex] [text] COLLATE Latin1_General_CI_AI NULL,
[Wis] [text] COLLATE Latin1_General_CI_AI NULL,
[Con] [text] COLLATE Latin1_General_CI_AI NULL,
[Agi] [text] COLLATE Latin1_General_CI_AI NULL,
[UpHpMin] [text] COLLATE Latin1_General_CI_AI NULL,
[UpHpMax] [text] COLLATE Latin1_General_CI_AI NULL,
[UpMpMin] [text] COLLATE Latin1_General_CI_AI NULL,
[UpMpMax] [text] COLLATE Latin1_General_CI_AI NULL,
[UpStMin] [text] COLLATE Latin1_General_CI_AI NULL,
[UpStMax] [text] COLLATE Latin1_General_CI_AI NULL,
[LvUpSt] [text] COLLATE Latin1_General_CI_AI NULL,
[ReHp] [text] COLLATE Latin1_General_CI_AI NULL,
[ReMp] [text] COLLATE Latin1_General_CI_AI NULL,
[ReHpSec] [text] COLLATE Latin1_General_CI_AI NULL,
[ReMpSec] [text] COLLATE Latin1_General_CI_AI NULL,
[Hp] [text] COLLATE Latin1_General_CI_AI NULL,
[Mp] [text] COLLATE Latin1_General_CI_AI NULL,
[St] [text] COLLATE Latin1_General_CI_AI NULL,
[Wp] [text] COLLATE Latin1_General_CI_AI NULL,
[DecSt] [text] COLLATE Latin1_General_CI_AI NULL,
[ReWalkSt] [text] COLLATE Latin1_General_CI_AI NULL,
[ReStandSt] [text] COLLATE Latin1_General_CI_AI NULL,
[ReStSec] [text] COLLATE Latin1_General_CI_AI NULL,
[Mr] [text] COLLATE Latin1_General_CI_AI NULL,
[UpMr] [text] COLLATE Latin1_General_CI_AI NULL,
[LvUpMr] [text] COLLATE Latin1_General_CI_AI NULL,
[Ats] [text] COLLATE Latin1_General_CI_AI NULL,
[Mvs] [text] COLLATE Latin1_General_CI_AI NULL,
[Cats] [text] COLLATE Latin1_General_CI_AI NULL,
[Sr] [text] COLLATE Latin1_General_CI_AI NULL
) ON [PRIMARY]
GO
