CREATE TABLE [dbo].[KING_CANDIDACY_NOTICE_BOARD]
(
[strUserID] [char] (21) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[byNation] [tinyint] NOT NULL,
[sNoticeLen] [smallint] NOT NULL,
[strNotice] [varbinary] (1024) NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[KING_CANDIDACY_NOTICE_BOARD] ADD CONSTRAINT [PK_KING_CANDIDACY_NOTICE_BOARD] PRIMARY KEY CLUSTERED  ([strUserID]) ON [PRIMARY]
GO
