CREATE TABLE [dbo].[KING_SYSTEM]
(
[byNation] [tinyint] NOT NULL,
[byType] [tinyint] NOT NULL,
[sYear] [smallint] NOT NULL,
[byMonth] [tinyint] NOT NULL,
[byDay] [tinyint] NOT NULL,
[byHour] [tinyint] NOT NULL,
[byMinute] [tinyint] NOT NULL,
[byImType] [tinyint] NOT NULL,
[sImYear] [smallint] NOT NULL,
[byImMonth] [tinyint] NOT NULL,
[byImDay] [tinyint] NOT NULL,
[byImHour] [tinyint] NOT NULL,
[byImMinute] [tinyint] NOT NULL,
[byNoahEvent] [tinyint] NOT NULL CONSTRAINT [DF_KING_SYSTEM_byNoahEvent] DEFAULT (0),
[byNoahEvent_Day] [tinyint] NOT NULL,
[byNoahEvent_Hour] [tinyint] NOT NULL,
[byNoahEvent_Minute] [tinyint] NOT NULL,
[sNoahEvent_Duration] [smallint] NOT NULL,
[byExpEvent] [tinyint] NOT NULL CONSTRAINT [DF_KING_SYSTEM_byExpEvent] DEFAULT (0),
[byExpEvent_Day] [tinyint] NOT NULL,
[byExpEvent_Hour] [tinyint] NOT NULL,
[byExpEvent_Minute] [tinyint] NOT NULL,
[sExpEvent_Duration] [smallint] NOT NULL,
[nTribute] [int] NOT NULL CONSTRAINT [DF_KING_SYSTEM_nTribute] DEFAULT (0),
[byTerritoryTariff] [tinyint] NOT NULL CONSTRAINT [DF_KING_SYSTEM_byTerritoryTariff] DEFAULT (0),
[nTerritoryTax] [int] NOT NULL CONSTRAINT [DF_KING_SYSTEM_nTerritoryTax] DEFAULT (0),
[nNationalTreasury] [int] NOT NULL CONSTRAINT [DF_KING_SYSTEM_nNationalTreasury] DEFAULT (0),
[strKingName] [char] (21) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[strImRequestID] [char] (21) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
