CREATE TABLE [dbo].[MAGIC_TYPE4]
(
[iNum] [int] NULL,
[Name] [char] (30) COLLATE Latin1_General_CI_AS NULL,
[Description] [char] (100) COLLATE Latin1_General_CI_AS NULL,
[BuffType] [tinyint] NULL,
[Radius] [tinyint] NULL,
[Duration] [smallint] NULL,
[AttackSpeed] [tinyint] NULL,
[Speed] [tinyint] NULL,
[AC] [smallint] NULL,
[ACPct] [smallint] NULL,
[Attack] [tinyint] NULL,
[MagicAttack] [tinyint] NULL,
[MaxHP] [smallint] NULL,
[MaxHpPct] [smallint] NULL,
[MaxMP] [smallint] NULL,
[MaxMpPct] [smallint] NULL,
[HitRate] [tinyint] NULL,
[AvoidRate] [smallint] NULL,
[Str] [smallint] NULL,
[Sta] [smallint] NULL,
[Dex] [smallint] NULL,
[Intel] [smallint] NULL,
[Cha] [smallint] NULL,
[FireR] [tinyint] NULL,
[ColdR] [tinyint] NULL,
[LightningR] [tinyint] NULL,
[MagicR] [tinyint] NULL,
[DiseaseR] [tinyint] NULL,
[PoisonR] [tinyint] NULL,
[ExpPct] [tinyint] NULL
) ON [PRIMARY]
GO
